[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "together"
version = "0.0.1"
authors = [
  { name="Together Computer", email="community@together.xyz" },
]
description = "Coming soon!"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
]

dependencies = [
    "typer",
    "requests",
]

[project.optional-dependencies]
quality = ["black~=23.1", "ruff>=0.0.241,<=0.0.259"]

[project.urls]
"Homepage" = "https://github.com/togethercomputer/together"
"Bug Tracker" = "https://github.com/togethercomputer/together/issues"

[project.scripts]
together = "together.cli:main"
